### ISSUE TITLE
Nuxt 3.7.0 currently broken with VueFire

### ISSUE THREAD

**Issue by posva** [vuejs/vuefire#1421]
The current version of Nuxt (3.7.0) doesn't work with nuxt-vuefire. Downgrade to 3.6.5 until this is fixed

Opened https://github.com/nuxt/nuxt/issues/22918 to add more info

**Comment by luc122c** [comment]
I was just about to post an issue for this. I'm getting `Component app-check has not been registered yet` after upgrading to Nuxt 3.7.0.

```
[nuxt] [request error] [unhandled] [500] Component app-check has not been registered yet
  at Provider.Provider.initialize (./node_modules/@firebase/component/src/provider.ts:239:13)  
  at initializeAppCheck (./node_modules/@firebase/app-check/src/api.ts:105:29)  
  at Module.VueFireAppCheckServer (./node_modules/vuefire/dist/server/index.mjs:107:20)  
  at ./node_modules/nuxt-vuefire/dist/runtime/app-check/plugin.server.mjs:13:25  
  at ./virtual:nuxt:/Users/luc122c/Dev/pixel.stream/.nuxt/plugins/server.mjs:50:89  
  at Module.executeAsync (./node_modules/unctx/dist/index.mjs:111:19)  
  at setup (./virtual:nuxt:/Users/luc122c/Dev/pixel.stream/.nuxt/plugins/server.mjs:50:65)  
  at ./node_modules/nuxt/dist/app/nuxt.js:114:60  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:162:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)
  ```

**Comment by posva** [comment]
Yes, the problem could either come from Firebase, Nuxt, or this module. Still don't know why this is happening but I suspect it's related to some deduping issue as it works locally in this mono repo. Any help is welcome, until then, downgrade Nuxt or disable app-check.

**Comment by gsavvidis96** [comment]
Having an auth middleware like stated in the docs

```
// middleware/auth.ts

export default defineNuxtRouteMiddleware(async (to, from) => {
  const user = await getCurrentUser();

  console.log(user);

  // redirect the user to the login page
  if (!user) {
    return navigateTo({
      path: "/login",
      query: {
        redirect: to.fullPath,
      },
    });
  }
});
```

```
// pages/index.vue

<template>
  <div>
    <h1>Home</h1>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: ["auth"],
});
</script>

<style lang="scss" scoped></style>
```

results in an error:  

> Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).

Although in a component I am able to get the current user while rendered server side.

```
// login.vue

<template>
  <div>
    <h1>Login</h1>
  </div>
</template>

<script setup lang="ts">
const user = useCurrentUser();

console.log(user.value);
</script>

<style scoped></style>
```

When using nuxt@3.6.5 the above examples work as expected. Only happens using nuxt@3.7.0

**Comment by posva** [comment]
This got fixed upstream and should be good on the next release of Nuxt.

**Comment by posva** [comment]
BTW, You can test locally with https://nuxt.com/docs/guide/going-further/edge-channel/#edge-release-channel until a new version of Nuxt is releasing (probably 3.7.1)

**Comment by dosstx** [comment]
About to give Vuefire a try again. Can someone confirm that using Nuxt 3.7.1 fixes the problem for this issue?

**Comment by posva** [comment]
It is fixed

**Comment by fayazara** [comment]
I am still getting this issue in nuxt 3.8.0 @posva 
![Screenshot 01-11 at 17](https://github.com/vuejs/vuefire/assets/15716057/95c1db30-0846-493c-8c4c-ecd3923eee22)

Package versions
```
"vuefire": "^3.1.17"
"nuxt-vuefire": "^0.4.0",
"nuxt": "^3.8.0",
```

**Comment by posva** [comment]
This shouldn’t come from VueFire as the code hasn’t changed in a while. It could be a bug in your code or from Nuxt

**Comment by fayazara** [comment]
Let me try to reproduce this.

**Comment by fayazara** [comment]
Thank you for the response, looking into the repro template and will try to recreate our project the same way.

Just curious, what do you mean by "You haven’t configured your project." 🤔

**Comment by fayazara** [comment]
Just cloned and checked that upgrading the spark plan template does not work on nuxt version 3.8.0.
![Screenshot 01-11 at 19](https://github.com/vuejs/vuefire/assets/15716057/d4137460-ff4a-4efd-8734-257bdd1d98c8)

CC: @posva

**Comment by posva** [comment]
Just tested myself and it's working properly. You probably didn't have the credentials or didn't use the emulators. I even updated the dependencies. Feel free to give it another look and good luck!

**Comment by fayazara** [comment]
Is it necessary to use the emulator? 

We're only using the auth and nothing else.

**Comment by fayazara** [comment]
Ah, I just added service-account.json in our root with the environment variable and it looks like it's working now. 

This was not clear from the docs, I will try to update the docs and make a PR. Thank you for he help and assistance. 🫡

**Comment by wjlee2020** [comment]
@fayazara 
curious, do we need the service-account.json if we aren't planning on using ssr?

**Comment by marcustoy** [comment]
> Ah, I just added service-account.json in our root with the environment variable and it looks like it's working now.
> 
> This was not clear from the docs, I will try to update the docs and make a PR. Thank you for he help and assistance. 🫡

Somehow adding a service-account.json file works for me as well. Thanks @fayazara !

**Comment by dievonde** [comment]
> [@fayazara](https://github.com/fayazara) curious, do we need the service-account.json if we aren't planning on using ssr? for me, the `initializeApp` error goes away when I set ssr: false in my nuxt config, however i get a auth/invalid-credential error from firebase since I'm not calling initalizeApp()

explicitly disabling SSR by setting `ssr: false,` in Nuxt config seems to fix this issue
